### ISSUE TITLE
steembase.storage.WrongMasterPasswordException when using correct password calling feed

### ISSUE THREAD

**Issue by robrigo** [Netherdrake/conductor#1]
Hello,

I am currently using conductor to aid in setting up a witness node. I have set UNLOCK in my environment to my BIP38 wallet password. This works great when calling `conductor update`, but I get a stack trace when trying to call `conductor feed`. I'm not entirely sure why the password is working in one scenario and considered bad in the other. Any ideas? Here's the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/steembase/storage.py", line 409, in decryptEncryptedMaster
    decrypted_master = aes.decrypt(encrypted_master)
  File "/usr/local/lib/python3.5/dist-packages/steem/aes.py", line 40, in decrypt
    return self._unpad(cipher.decrypt(enc[AES.block_size:])).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conductor/feeds.py", line 70, in run_price_feeds
    refresh_price_feeds(witness('name'))
  File "/usr/local/lib/python3.5/dist-packages/conductor/feeds.py", line 51, in refresh_price_feeds
    steem.commit.witness_feed_publish(steem_usd, quote=quote, account=witness_name)
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 858, in witness_feed_publish
    return self.finalizeOp(op, account, "active")
  File "/usr/local/lib/python3.5/dist-packages/steem/commit.py", line 125, in finalizeOp
    tx.appendSigner(account, permission)
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 67, in appendSigner
    keys = fetchkeys(account)
  File "/usr/local/lib/python3.5/dist-packages/steem/transactionbuilder.py", line 55, in fetchkeys
    wif = self.wallet.getPrivateKeyForPublicKey(authority[0])
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 232, in getPrivateKeyForPublicKey
    return self.decrypt_wif(self.keyStorage.getPrivateKeyForPublicKey(pub))
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 163, in decrypt_wif
    self.unlock()
  File "/usr/local/lib/python3.5/dist-packages/steem/wallet.py", line 100, in unlock
    masterpwd = self.MasterPassword(pwd)
  File "/usr/local/lib/python3.5/dist-packages/steembase/storage.py", line 401, in __init__
    self.decryptEncryptedMaster()
  File "/usr/local/lib/python3.5/dist-packages/steembase/storage.py", line 411, in decryptEncryptedMaster
    raise WrongMasterPasswordException
steembase.storage.WrongMasterPasswordException
```

**Comment by Netherdrake** [comment]
I am unable to reproduce this issue. Does your steempy wallet password contain any strange characters? 

What version of Python are you running?

**Comment by robrigo** [comment]
Ah, my wallet password does have a caret symbol in it. Funny how it works in some scenarios and not others!

**Comment by robrigo** [comment]
Changing my password to one without symbols fixed the problem. I suppose a good feature would be to disallow passwords that have interoperability problems (invalid chars). Thanks for looking into it @furion.

**Comment by Netherdrake** [comment]
Please try the latest version. There was a bug in the unlock code, fixed in https://github.com/Netherdrake/conductor/commit/0275454f25d227690a1e594bc5b666b0c9402676
