### ISSUE TITLE
not able to use conductor feed

### ISSUE THREAD

**Issue by 4Ykw** [Netherdrake/conductor#11]
Hi furion,

Any guesses I might e missing here? Works well with the rest.

I am using Ubuntu 16.04.3 LTS

```
Thu Nov 30 14:14:43 2017
Old Price: 1.167
New Price: 0.994

Current STEEM price: 0.994 USD
Current SBD price: 1.245 USD
Quote: 1.000 STEEM

Spread between prices: 17.404%
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/conductor/feeds.py", line 60, in run_price_feeds
    refresh_price_feeds(witness('name'), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/conductor/feeds.py", line 50, in refresh_price_feeds
    steem.commit.witness_feed_publish(steem_usd, quote=quote, account=witness_name)
  File "/home/user/.local/lib/python3.5/site-packages/steem/commit.py", line 858, in witness_feed_publish
    return self.finalizeOp(op, account, "active")
  File "/home/user/.local/lib/python3.5/site-packages/steem/commit.py", line 126, in finalizeOp
    tx.sign()
  File "/home/user/.local/lib/python3.5/site-packages/steem/transactionbuilder.py", line 108, in sign
    raise MissingKeyError
steembase.exceptions.MissingKeyError

```

**Comment by 4Ykw** [comment]
My key is wrong... sorry.
