### ISSUE TITLE
Conductor not compatible with funcy update

### ISSUE THREAD

**Issue by Someguy123** [Netherdrake/conductor#21]
On new conductor installs I run into this issue:

```
└─[$] <git:(master)> conductor status
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 7, in <module>
    from conductor.cli import conductor
  File "/usr/local/lib/python3.6/dist-packages/conductor/cli.py", line 6, in <module>
    from funcy import silent
ImportError: cannot import name 'silent'
```

Either you need to upgrade conductor to be compatible with the new funcy, or you need to lock in the older version 1.10 into requirements.txt

e.g. I did this and conductor worked again:

```
pip3 install -U funcy==1.10
```

**Comment by Someguy123** [comment]
If anyone gets any other issues related to package update incompatibility, here's the output of `pip3 freeze` on one of my systems where conductor works fine:

```
appdirs==1.4.3
certifi==2018.1.18
chardet==3.0.4
click==6.7
click-spinner==0.1.7
conductor==0.3.2
dateparser==0.6.0
diff-match-patch==20121119
ecdsa==0.13
funcy==1.10
humanize==0.5.1
idna==2.6
langdetect==1.0.7
maya==0.3.3
pendulum==1.4.1
prettytable==0.7.2
pycrypto==2.6.1
pyinotify==0.9.6
pylibscrypt==1.7.1
python-dateutil==2.6.1
python-systemd==231
pytz==2017.3
pytzdata==2018.3
regex==2018.2.3
requests==2.18.4
ruamel.yaml==0.15.35
scrypt==0.8.3
six==1.11.0
steem==0.18.95
tabulate==0.8.2
toolz==0.9.0
tzlocal==1.5.1
ujson==1.35
urllib3==1.22
voluptuous==0.10.5
w3lib==1.19.0
```

Dump that into a file called requirements.txt and then do `pip3 install -U -r requirements.txt` and your conductor should be working again.

Some of these packages might not be required, but since conductor was installed globally I can't isolate which packages actually matter.
